# Generated by Django 2.2.7 on 2019-12-17 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0002_auto_20191217_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='PostPage',
            new_name='Post',
        ),
    ]
