# Generated by Django 2.2.7 on 2019-12-18 02:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0005_blogtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogIndex',
        ),
        migrations.RenameModel(
            old_name='BlogTag',
            new_name='BlogTagIndex',
        ),
    ]
