# Generated by Django 2.2.7 on 2019-12-27 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191226_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Nickname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='job_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Job title'),
        ),
    ]
